const articulosConstitucion = {
  "1": "Principios básicos",
  "2": "Unidad y autonomía",
  "3": "Idioma",
  "4": "Bandera",
  "5": "Capital del Estado",
  "6": "Partidos políticos",
  "7": "Sindicatos y asociaciones empresariales",
  "8": "Fuerzas armadas",
  "9": "Principios constitucionales",
  "10": "Derechos y deberes fundamentales",
  "11": "Nacionalidad",
  "12": "Mayoría de edad",
  "13": "Derechos de españoles y extranjeros",
  "14": "Principio de igualdad",
  "15": "Derecho a la vida",
  "16": "Libertad ideológica, religiosa y de culto",
  "17": "Derecho a la libertad y a la seguridad",
  "17.1": "Libertad y seguridad",
  "17.2": "Detención preventiva",
  "17.3": "Derechos de las personas detenidas",
  "17.4": "Habeas corpus y prisión provisional",
  "18": "Derecho al honor, a la intimidad personal y familiar y a la propia imagen",
  "18.2": "Inviolabilidad del domicilio",
  "18.3": "Secreto de las comunicaciones",
  "19": "Libertad de residencia y circulación",
  "20": "Libertad de expresión",
  "20.1 a)": "Expresar y difundir librem. pensamientos, ideas y opiniones",
  "20.1 d)": "Comunicar o recibir librem. información veraz por cualquier medio de difusión",
  "20.5": "Secuestro de publicaciones, grabaciones y otros medios de información",
  "21": "Derecho de reunión y manifestación",
  "22": "Derecho de asociación",
  "23": "Derecho de participación en los asuntos públicos",
  "24": "Derecho a la tutela judicial efectiva",
  "25": "Sanciones, condenas y penas privativas de libertad",
  "26": "Prohibición de los tribunales de honor",
  "27": "Derecho a la educación",
  "28": "Libertad sindical. Derecho a huelga",
  "28.2": "Derecho a la huelga",
  "29": "Derecho de petición",
  "30": "Defensa de España",
  "31": "Principio de capacidad económica y no confiscatoriedad",
  "32": "Derecho a contraer matrimonio",
  "33": "Derecho a la propiedad privada y la herencia",
  "34": "Derecho de fundación",
  "35": "Derecho al trabajo",
  "36": "Colegios profesionales",
  "37": "Derecho a la negociación colectiva laboral",
  "37.2": "Derecho a la adopción de medidas de conflicto colectivo",
  "38": "Libertad de empresa",
  "39": "Protección de la familia y de la infancia",
  "40": "Protección del trabajador",
  "41": "Seguridad Social",
  "42": "Protección de los trabajadores españoles en el extranjero",
  "43": "Derecho a la protección de la salud",
  "44": "Acceso a la cultura y promoción de la investigación",
  "45": "Medio ambiente",
  "46": "Conservación del patrimonio histórico, cultural y artístico",
  "47": "Vivienda",
  "48": "Participación de la juventud en el desarrollo político, social, económico y cultural",
  "49": "Personas con discapacidad",
  "50": "Pensiones",
  "51": "Defensa de los consumidores y usuarios",
  "52": "Organizaciones profesionales",
  "53": "Garantías, libertades y derechos fundamentales",
  "54": "Defensor del pueblo",
  "55": "Suspensión de los derechos y libertades"
};

